spring:
   application:
      name: Task
      
   datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/challenger?zeroDateTimeBehavior=convertToNull&serverTimezone=America/Sao_Paulo&useSSL=false&allowPublicKeyRetrieval=true   
   
    
   jpa: 
    database: MYSQL
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        locationId:
          new_generator_mappings: false
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        jdbc:
          time_zone: UTC

baseurl:
      v1: /task/v1

server:
  port: 8000 
  


